# Generated by Django 5.2.6 on 2025-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitcases', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='value',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='question_options', to='suitcases.category'),
        ),
    ]
