# Generated by Django 5.2.6 on 2025-11-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_questionoption_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.CharField(max_length=360),
        ),
    ]
