# Generated by Django 5.2.6 on 2025-11-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_quizquestion_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='order',
        ),
    ]
