# Generated by Django 5.2.6 on 2025-12-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_questionoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question_order',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
